<script setup lang="ts">
import { storeToRefs } from 'pinia'
import type { CommunityPostType } from '@ai-learning-hub/contracts'
import { useCommunityStore } from '../stores/community'
import { useAuthStore } from '../stores/auth'
import { useCommunityDraft } from './composables/useCommunityDraft'
import CommunityBlocks from './CommunityBlocks.vue'
import { postLabels } from './labels'
const editor = useCommunityDraft(), store = useCommunityStore(), auth = useAuthStore()
const paste = (event: ClipboardEvent) => { const files = Array.from(event.clipboardData?.files || []); if (files.length) { event.preventDefault(); void editor.uploadFiles(files) } }
const drop = (event: DragEvent) => { event.preventDefault(); void editor.uploadFiles(Array.from(event.dataTransfer?.files || [])) }
const keydown = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') { event.preventDefault(); void editor.save() }; if (event.key === 'Escape') { event.stopPropagation(); editor.close() } }
const { form, body, code, language, quote, images, topics, bindingType, bindingId, bindingSearch, bindingTitles, bindingOptions, source, preview, saving, bindingLoading, error, blocks, advanced, savedAt } = storeToRefs(editor)
const { save, upload, loadOptions, addBinding } = editor
</script>
<template>
  <form class="dialog-form composer-form" @submit.prevent="save()" @keydown="keydown" @paste="paste" @dragover.prevent @drop="drop">
    <header class="composer-mobile-top"><button type="button" class="text-link" @click="editor.close()">取消</button><select v-model="form.type" aria-label="发布内容类型"><option v-for="(label, type) in postLabels" :key="type" :value="type">{{ label }}</option></select><button class="button primary small" type="submit" :disabled="saving">{{ saving ? '保存中…' : '发布' }}</button></header>
    <div class="composer-row"><label>内容类型<select v-model="form.type"><option v-for="(label, type) in postLabels" :key="type" :value="type as CommunityPostType">{{ label }}</option></select></label><details><summary>可见范围：{{ form.visibility === 'school' ? '仅同校用户' : '登录社区用户' }}</summary><label>可见范围<select v-model="form.visibility"><option value="public">登录社区用户</option><option value="school">仅同校用户</option></select></label></details></div>
    <label v-if="advanced || ['question', 'project'].includes(form.type)">标题{{ ['question', 'project'].includes(form.type) ? '（必填）' : '（选填）' }}<input v-model="form.title" maxlength="160" :required="['question', 'project'].includes(form.type)" placeholder="让同学更容易理解你的问题或收获" /></label>
    <template v-if="!preview"><label>正文<textarea v-model="body" rows="6" maxlength="15000" required placeholder="说明学习背景、尝试过的方法，以及你的发现……" /></label><details v-if="advanced"><summary>添加代码或引用</summary><label>代码语言<input v-model="language" maxlength="30" /></label><label>代码块（仅展示，不执行）<textarea v-model="code" rows="4" maxlength="12000" /></label><label>引用<textarea v-model="quote" rows="2" maxlength="2000" /></label></details><label>学习图片（最多 4 张，每张 5MB）<input type="file" multiple accept="image/png,image/jpeg,image/webp" :disabled="saving" @change="upload" /></label><div v-for="(image, index) in images" :key="image.fileId" class="composer-row"><input v-model="image.alt" aria-label="图片说明" maxlength="200" /><button class="text-link" type="button" @click="images.splice(index, 1)">移除</button></div></template>
    <CommunityBlocks v-else :blocks="blocks" />
    <details><summary>添加学习关联（{{ advanced ? 8 : 1 }} 项）</summary><fieldset><p class="muted">按需查找已发布学习内容。本人实训成果请从实训工作台分享带入。</p><div class="composer-row"><select v-model="bindingType" aria-label="关联类型"><option v-for="(label, type) in { theme: '学习主题', course: '课程', lesson: '课时', lab: '实训', resource: '资源', article: '文章', challenge: '挑战', lab_run: '已提交实训记录' }" :key="type" :value="type">{{ label }}</option></select><template v-if="source"><input v-model="bindingSearch" placeholder="按标题查找" aria-label="查找关联学习内容" @keydown.enter.prevent="loadOptions" /><button class="button secondary small" type="button" :disabled="bindingLoading" @click="loadOptions">查找</button></template></div><div class="composer-row"><select v-if="source" v-model="bindingId" aria-label="关联学习内容" :disabled="bindingLoading"><option value="">{{ bindingLoading ? '读取中…' : '请选择学习内容' }}</option><option v-for="item in bindingOptions" :key="item.id" :value="item.id">{{ item.title }}</option></select><input v-else v-model="bindingId" placeholder="从本人学习记录取得的标识" aria-label="关联内容标识" /><button class="button secondary small" type="button" :disabled="!bindingId" @click="addBinding">关联</button></div><div class="community-topic-list"><button v-for="(binding, index) in form.bindings" :key="`${binding.type}:${binding.id}`" type="button" class="community-chip" @click="form.bindings.splice(index, 1)">{{ bindingTitles[`${binding.type}:${binding.id}`] || binding.id }} ×</button></div></fieldset></details>
    <details><summary>设置话题</summary><fieldset><legend>学习话题（最多 {{ advanced ? 5 : 3 }} 项）</legend><div class="composer-topics"><label v-for="topic in topics" :key="topic.id"><input v-model="form.topicIds" type="checkbox" :value="topic.id" :disabled="form.topicIds.length >= (advanced ? 5 : 3) && !form.topicIds.includes(topic.id)" />{{ topic.name }}</label></div></fieldset></details>
    <p v-if="auth.dataMode === 'mock'" class="community-notice">演示图片仅保存在当前浏览器会话，不代表真实上传。</p><p class="composer-privacy">仅发布你确认分享的内容；请勿包含私密笔记、完整成绩、实训日志或密钥。成就草稿不会自动公开。</p><p v-if="error" role="alert" class="community-error">{{ error }}</p>
    <p v-if="savedAt" role="status" class="muted">{{ savedAt }}</p><div class="composer-actions"><button v-if="!advanced" class="text-link" type="button" @click="store.composerMode = 'advanced'; store.composerInline = false">高级编辑</button><RouterLink to="/community/drafts">草稿箱</RouterLink><button v-if="advanced" class="button secondary" type="button" @click="preview = !preview">{{ preview ? '继续编辑' : '发布预览' }}</button><button class="button secondary" type="button" :disabled="saving" @click="save(true)">保存草稿</button><button class="button primary" type="submit" :disabled="saving">{{ saving ? '正在保存…' : '确认发布' }}</button></div>
  </form>
</template>
